import pypdf
from Character_Class import Character

reader = pypdf.PdfReader("DnD_5E_CharacterSheet_FormFillable.pdf")
writer = pypdf.PdfWriter()

Char = Character()
Char.parse('Characters/James Teq.json')


writer.add_page(reader.pages[0])
writer.add_page(reader.pages[1])
writer.add_page(reader.pages[2])
fields = reader.get_fields()
writer.append(reader)

def Update_Field(Page:str,Field:str,Value:str):
    writer.update_page_form_field_values(
        writer.pages[Page], 
        {Field: Value},
        auto_regenerate=False
    )

#for field in fields:
#    print((field))

data = Char.data

#Character Info

Update_Field(0,'Race',data['Race'])
Update_Field(0,'CharacterName',data['Name'])
Update_Field(0,'PlayerName','Autogenerated')
Update_Field(0,'ClassLevel',f"{data['Starting_Class']} {data['Total_Level']}")
Update_Field(0,'Background','Acolyte')
Update_Field(0,'Alignment','Lawful Good')

#Ability Scores

Update_Field(0,'STR',data['Scores']['str'])
Update_Field(0,'STRmod',Char.modifier_calculator(data['Scores']['str']))
Update_Field(0,'DEX',data['Scores']['dex'])
Update_Field(0,'DEXmod',Char.modifier_calculator(data['Scores']['dex']))
Update_Field(0,'CON',data['Scores']['con'])
Update_Field(0,'CONmod',Char.modifier_calculator(data['Scores']['con']))
Update_Field(0,'INT',data['Scores']['int'])
Update_Field(0,'INTmod',Char.modifier_calculator(data['Scores']['int']))
Update_Field(0,'WIS',data['Scores']['wis'])
Update_Field(0,'WISmod',Char.modifier_calculator(data['Scores']['wis']))
Update_Field(0,'CHA',data['Scores']['cha'])
Update_Field(0,'CHAmod',Char.modifier_calculator(data['Scores']['cha']))

#Passives

Update_Field(0,'Initiative',(('+'+str(Char.modifier_calculator(data['Scores']['dex'])))))
Update_Field(0,'Passive',(Char.modifier_calculator(data['Scores']['wis'])+10))

# Number Stuff

Update_Field(0,'ProfBonus','+2')
Update_Field(0,'AC',data['Armor_Class'])
Update_Field(0,'Speed',data['Walking_Speed'])
Update_Field(0,'HPMax',data['Health'])
Update_Field(0,'HPCurrent',data['Current_Health'])
Update_Field(0,'HD',f"d{data['Hit_Dice']}")

#Saving Throws

Update_Field(0,'ST Strength', 'N/A')
Update_Field(0,'Check Box 11','Yes')
Update_Field(0,'ST Dexterity', 'N/A')
Update_Field(0,'Check Box 18','Yes')
Update_Field(0,'ST Constitution', 'N/A')
Update_Field(0,'Check Box 19','Yes')
Update_Field(0,'ST Intelligence', 'N/A')
Update_Field(0,'Check Box 20','Yes')
Update_Field(0,'ST Wisdom', 'N/A')
Update_Field(0,'Check Box 21','Yes')
Update_Field(0,'ST Charisma', 'N/A')
Update_Field(0,'Check Box 22','Yes')

#Successes on death saves
#Update_Field(0,'Check Box 12','Yes')
#Update_Field(0,'Check Box 13','Yes')
#Update_Field(0,'Check Box 14','Yes')

#Skills and profiency

Update_Field(0,'Acrobatics','N')
Update_Field(0,'Check Box 23','Yes')
Update_Field(0,'Animal','N')
Update_Field(0,'Check Box 24','Yes')
Update_Field(0,'Athletics','N')
Update_Field(0,'Check Box 25','Yes')
Update_Field(0,'Deception','N')
Update_Field(0,'Check Box 26','Yes')
Update_Field(0,'History','N')
Update_Field(0,'Check Box 27','Yes')
Update_Field(0,'Insight','N')
Update_Field(0,'Check Box 28','Yes')
Update_Field(0,'Intimidation','N')
Update_Field(0,'Check Box 29','Yes')
Update_Field(0,'Investigation','N')
Update_Field(0,'Check Box 30','Yes')
Update_Field(0,'Arcana','N')
Update_Field(0,'Check Box 31','Yes')
Update_Field(0,'Perception','N')
Update_Field(0,'Check Box 32','Yes')
Update_Field(0,'Nature','N')
Update_Field(0,'Check Box 33','Yes')
Update_Field(0,'Performance','N')
Update_Field(0,'Check Box 34','Yes')
Update_Field(0,'Medicine','N')
Update_Field(0,'Check Box 35','Yes')
Update_Field(0,'Religion','N')
Update_Field(0,'Check Box 36','Yes')
Update_Field(0,'Stealth','N')
Update_Field(0,'Check Box 37','Yes')
Update_Field(0,'Persuasion','N')
Update_Field(0,'Check Box 38','Yes')
Update_Field(0,'SleightofHand','N')
Update_Field(0,'Check Box 39','Yes')
Update_Field(0,'Survival','N')
Update_Field(0,'Check Box 40','Yes')

#Money

Update_Field(0,'CP','0')
Update_Field(0,'SP','0')
Update_Field(0,'EP','0')
Update_Field(0,'GP','0')
Update_Field(0,'PP','0')


# Page 2

Update_Field(1,'CharacterName 2', 'James Teq')
Update_Field(1,'FactionName','The Insurgency')

with open("filled-out.pdf", "wb") as output_stream:
    writer.write(output_stream)